[workspace]
resolver = "2"
members = ["linker"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["kei519 <masaki.keigo.q00@kyoto-u.jp>"]
description = "Front-end Rust Compiler for studying."
readme = "README.md"
